#!/usr/bin/with-contenv bash

# pre steps
echo 'pre steps' && \
pip3 install --upgrade pip && \
pip3 install virtualenv && \
virtualenv -p python3 /virt && \
source /virt/bin/activate

# clone repository
echo 'cloning bamf' && \
git clone https://github.com/bpepple/bamf.git

# put it inside /virt
echo 'copying repository to working directory' && \
cp -r /bamf/* /virt && \
cd /virt && \
bin/pip3 install redis Pillow PyPDF2 && \
sed -i "/psycopg2/d" requirements.txt
sed -i "s/requests-cache/requests_cache/g" bamf/settings.py && \
bin/pip3 install -r requirements.txt

# edit database config
echo 'editing settings' && \
sed -i "s/'ALLOWED_HOSTS': [],/'ALLOWED_HOSTS': ['*'],/g" bamf/settings.py && \
sed -i "s/'ENGINE': 'django.db.backends.postgresql',/'ENGINE': 'django.db.backends.sqlite3',/g" bamf/settings.py && \
sed -i "s/'NAME': 'bamfproject',/'NAME': '/virt/sqlite.db',/g" bamf/settings.py && \
grep -qxF "/'USER': 'bpepple'" || sed -i "/'USER': 'bpepple'/d" bamf/settings.py && \
grep -qxF "/'PASSWORD': 'bamfpassword'" || sed -i "/'PASSWORD': 'bamfpassword'/d" bamf/settings.py && \
grep -qxF "/'HOST': ''" || sed -i "/'HOST': ''/d" bamf/settings.py && \

echo 'setting database up' && \
bin/python3 manage.py generatesecretkey && \
bin/python3 manage.py migrate && \
bin/python3 manage.py createsuperuser --noinput --username admin --email no-reply@gmail.com && \
source /virt/bin/activate

# permissions
chown -R gamestream:gamestream \
	/virt
chmod -R g+w \
    /virt
