{
 "title": "Sombra",
 "description": "External drives capacity & network traffic",
 "tags": [ "system" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Main disk %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{device=\"/dev/nvme0n1p2\",instance=\"sombra.home:9100\"} - node_filesystem_avail_bytes{device=\"/dev/nvme0n1p2\",instance=\"sombra.home:9100\"}) / node_filesystem_size_bytes{device=\"/dev/nvme0n1p2\",instance=\"sombra.home:9100\"}  * 100"
    }
   ]
  },
  {
   "title": "WD2To External drive usage %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{device=\"/dev/sdb1\",instance=\"sombra.home:9100\"} - node_filesystem_avail_bytes{device=\"/dev/sdb1\",instance=\"sombra.home:9100\"}) / node_filesystem_size_bytes{device=\"/dev/sdb1\",instance=\"sombra.home:9100\"}  * 100"
    }
   ]
  },
  {
   "title": "WD1To External drive usage %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{device=\"/dev/sda2\",instance=\"sombra.home:9100\"} - node_filesystem_avail_bytes{device=\"/dev/sda2\",instance=\"sombra.home:9100\"}) / node_filesystem_size_bytes{device=\"/dev/sda2\",instance=\"sombra.home:9100\"}  * 100"
    }
   ]
  },
  {
   "title": "Main Disk free space",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/nvme0n1p2\",instance=\"sombra.home:9100\"}"
    }
   ]
  },
  {
   "title": "WD2To External drive free space",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/sdb1\",instance=\"sombra.home:9100\"}"
    }
   ]
  },
  {
   "title": "WD1To External drive free space",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{device=\"/dev/sda2\",instance=\"sombra.home:9100\"}"
    }
   ]
  },
  {
   "title": "Used Storage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 9 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/nvme0n1p2\",instance=\"sombra.home:9100\"} - node_filesystem_free_bytes{device=\"/dev/nvme0n1p2\",instance=\"sombra.home:9100\"}"
    }
   ]
  },
  {
   "title": "Used Storage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 9 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/sdb1\",instance=\"sombra.home:9100\"} - node_filesystem_free_bytes{device=\"/dev/sdb1\",instance=\"sombra.home:9100\"}"
    }
   ]
  },
  {
   "title": "Used Storage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 9 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/sda2\",instance=\"sombra.home:9100\"} - node_filesystem_free_bytes{device=\"/dev/sda2\",instance=\"sombra.home:9100\"}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=\"sombra.home:9100\",interface!~\"br.*|lo\"}[1m]))",
     "legendFormat": "In: en0"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=\"sombra.home:9100\",interface!~\"br.*|lo\"}[1m]))",
     "legendFormat": "Out: en0"
    }
   ]
  }
 ]
}