{
 "title": "Traefik Backend",
 "description": "Traefik dashboard prometheus",
 "tags": [
  "traefik",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "backend", "query": "label_values(backend)" }
  ]
 },
 "panels": [
  {
   "title": "Global stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests by service",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "expr": "sum(rate(traefik_backend_requests_total[1m])) by (backend) ",
       "legendFormat": "{{ backend }}"
      }
     ]
    },
    {
     "title": "Requests by protocol",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "expr": "sum(rate(traefik_entrypoint_requests_total{entrypoint =~ \"$entrypoint\"}[1m])) by (entrypoint) ",
       "legendFormat": "{{ entrypoint }}"
      }
     ]
    }
   ]
  },
  { "title": "$backend stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "$backend status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(traefik_backend_server_up{backend=\"$backend\"})/count(traefik_config_reloads_total)"
    }
   ]
  },
  {
   "title": "$backend return code",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (traefik_backend_requests_total{backend=\"$backend\"}) by (code)",
     "legendFormat": " {{code}}"
    }
   ]
  },
  {
   "title": "$backend method",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (traefik_backend_requests_total{backend=\"$backend\"}) by (method)",
     "legendFormat": " {{method}}"
    }
   ]
  },
  {
   "title": "Requests per minute",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{}[1m]))"
    }
   ]
  },
  {
   "title": "$backend response time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(traefik_backend_request_duration_seconds_sum{backend=\"$backend\"}) / sum(traefik_backend_requests_total{backend=\"$backend\"}) * 1000"
    }
   ]
  },
  {
   "title": "Request duration for $backend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_backend_request_duration_seconds_sum{backend=\"$backend\"}) / sum(traefik_backend_requests_total{backend=\"$backend\"}) * 1000"
    }
   ]
  },
  {
   "title": "Total requests over 1min $backend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=\"$backend\"}[1m]))",
     "legendFormat": "Total requests $backend"
    }
   ]
  },
  {
   "title": "Status codes over 1min for $backend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=\"$backend\"}[1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Method over 1min for $backend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=\"$backend\"}[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "Status codes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Status code 2XX over 1min for $backend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=\"$backend\",code=~\"2..\"}[1m])) by (method)",
     "legendFormat": "{{method}} "
    }
   ]
  },
  {
   "title": "Status code 3XX over 1min for $backend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=\"$backend\",code=~\"3..\"}[1m])) by (method)",
     "legendFormat": "{{method}} "
    }
   ]
  },
  {
   "title": "Status code 4XX over 1min for $backend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=\"$backend\",code=~\"4..\"}[1m])) by (method)",
     "legendFormat": "{{method}} "
    }
   ]
  },
  {
   "title": "Status code 5XX over 1min for $backend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=\"$backend\",code=~\"5..\"}[1m])) by (method)",
     "legendFormat": "{{method}} "
    }
   ]
  },
  {
   "title": "Status code 1XX over 1min for $backend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=\"$backend\",code=~\"1..\"}[1m])) by (method)",
     "legendFormat": "{{method}} "
    }
   ]
  },
  { "title": "Methods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "GET over 1min for $backend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=\"$backend\",method=\"GET\"}[1m])) by (code)",
     "legendFormat": "{{code}} "
    }
   ]
  },
  {
   "title": "POST over 1min for $backend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=\"$backend\",method=\"POST\"}[1m])) by (code)",
     "legendFormat": "{{code}} "
    }
   ]
  },
  {
   "title": "PUT over 1min for $backend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=\"$backend\",method=\"PUT\"}[1m])) by (code)",
     "legendFormat": "{{code}} "
    }
   ]
  },
  {
   "title": "DELETE over 1min for $backend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=\"$backend\",method=\"DELETE\"}[1m])) by (code)",
     "legendFormat": "{{code}} "
    }
   ]
  },
  {
   "title": "HEAD over 1min for $backend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=\"$backend\",method=\"HEAD\"}[1m])) by (code)",
     "legendFormat": "{{code}} "
    }
   ]
  },
  {
   "title": "OPTIONS over 1min for $backend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=\"$backend\",method=\"OPTIONS\"}[1m])) by (code)",
     "legendFormat": "{{code}} "
    }
   ]
  },
  {
   "title": "TRACE over 1min for $backend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=\"$backend\",method=\"TRACE\"}[1m])) by (code)",
     "legendFormat": "{{code}} "
    }
   ]
  },
  {
   "title": "CONNECT over 1min for $backend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=\"$backend\",method=\"CONNECT\"}[1m])) by (code)",
     "legendFormat": "{{code}} "
    }
   ]
  },
  {
   "title": "PATCH over 1min for $backend",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_backend_requests_total{backend=\"$backend\",method=\"PATCH\"}[1m])) by (code)",
     "legendFormat": "{{code}} "
    }
   ]
  }
 ]
}