heartbeat.monitors:
    - type: http
      id: transmission
      name: transmission
      schedule: '@every 5s'
      urls:
        - http://vpn-client:9091

    - type: http
      id: peerflix
      name: peerflix
      schedule: '@every 5s'
      urls:
        - http://vpn-client:9000

    - type: http
      id: deluge
      name: deluge
      schedule: '@every 5s'
      urls:
        - http://vpn-client:8112

    - type: http
      id: cloudtorrent
      name: cloudtorrent
      schedule: '@every 5s'
      urls:
        - http://vpn-client:3000

    - type: icmp
      id: chromecast
      name: chromecast
      schedule: '@every 5s'
      hosts:
        - 192.168.254.43

    - type: icmp
      id: pi
      name: pi
      schedule: '@every 5s'
      hosts:
        - 192.168.254.53

    - type: icmp
      id: lucio
      name: lucio
      schedule: '@every 5s'
      hosts:
        - 192.168.254.73

    - type: icmp
      id: gateway
      name: gateway
      schedule: '@every 5s'
      hosts:
        - 192.168.254.1

processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"

    - decode_json_fields:
        fields: ["message"]
        target: "json"
        overwrite_keys: true

output.logstash:
    hosts: ["logstash:5044"]

logging.json: true
logging.metrics.enabled: false
logging.level: warning
